# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- tags

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Compile'

- script: |
    npm run test:ci
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit.xml'

- task: Npm@1
  condition: contains(variables['Build.SourceBranch'], 'tags')
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '33d20382-05c7-4d49-8c46-ffe1c415612f'
